version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb"
    networks:
      - learn-memdb

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
    depends_on:
      - dynamodb-local
    networks:
      - learn-memdb

  dynamodb-table:
    image: amazon/aws-cli:latest
    entrypoint: "/bin/sh -c \"aws dynamodb create-table --region us-east-1 --table-name $${DYNAMO_TABLE_NAME} --attribute-definitions AttributeName=key,AttributeType=S --key-schema AttributeName=key,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamodb-local:8000\""
    volumes:
      - ~/.aws:/root/.aws
    env_file:
      - .env.local
    networks:
      - learn-memdb
    depends_on:
      - dynamodb-local
      - dynamodb-admin

  sqs-local:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - LEGACY_DIRECTORIES=1
    ports:
      - '4566:4566'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - learn-memdb

networks:
  learn-memdb:
    driver: bridge
